version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '22:00'
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
      time: "22:00"
    open-pull-requests-limit: 15
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "22:00"
    open-pull-requests-limit: 15
